### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/e-skGovCRZ#3]
When compiling e938a6d0db6dc9992276d1fdde7201ceb2072a8d, the test fails with this error:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running eu.comsode.unifiedviews.plugins.extractor.skgovcrz.SkGovCRZTest
10:23:32.405 [main] INFO  c.c.m.x.o.dpu.test.TestEnvironment - Creating cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment with workingDirectory /var/folders/vl/1zxq_7054yg61t2kpqlt2c100000gn/T/7412250632301033606
10:23:32.430 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Initializing NativeStore...
10:23:32.443 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - Data dir is /var/folders/vl/1zxq_7054yg61t2kpqlt2c100000gn/T/7412250632301033606/dataUnits/test_env_774511250
10:23:32.459 [main] DEBUG o.openrdf.sail.nativerdf.TripleStore - No indexes specified, using default indexes: spoc,posc
10:23:32.465 [main] DEBUG o.openrdf.sail.nativerdf.NativeStore - NativeStore initialized
10:23:32.515 [main] DEBUG o.o.query.parser.QueryParserRegistry - Registered service class org.openrdf.query.parser.serql.SeRQLParserFactory
10:23:32.523 [main] DEBUG o.o.query.parser.QueryParserRegistry - Registered service class org.openrdf.query.parser.sparql.SPARQLParserFactory
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.697 sec <<< FAILURE! - in eu.comsode.unifiedviews.plugins.extractor.skgovcrz.SkGovCRZTest
test(eu.comsode.unifiedviews.plugins.extractor.skgovcrz.SkGovCRZTest)  Time elapsed: 0.696 sec  <<< ERROR!
java.lang.Exception: Can not bind 'null' to output DataUnit: rdfOutput
    at cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment.connectDataUnits(TestEnvironment.java:480)
    at cz.cuni.mff.xrg.odcs.dpu.test.TestEnvironment.run(TestEnvironment.java:362)
    at eu.comsode.unifiedviews.plugins.extractor.skgovcrz.SkGovCRZTest.test(SkGovCRZTest.java:41)


Results :

Tests in error:
  SkGovCRZTest.test:41 »  Can not bind 'null' to output DataUnit: rdfOutput
```

**Comment by mbl-eea-sk** [comment]
Solved in https://github.com/comsode-uv-plugins/e-skGovCRZ/commit/e0146cafc95249e179756ec5de911b2f24f0cac3
