### ISSUE TITLE
 java.net.UnknownHostException: www.crz.gov.sk: Name or service not known

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/e-skGovCRZ#7]
After running for 20 hours, the DPU (compiled from 7167af10f9d811590fb72351fe0f5ea0fe66bcb4) failed with a  java.net.UnknownHostException exception:

```
Execution failed because: SkMartinContracts.execute.exceptioneu.unifiedviews.dpu.DPUException: SkMartinContracts.execute.exception
at eu.unifiedviews.helpers.dpu.context.ContextUtils.dpuException(ContextUtils.java:212)
at eu.comsode.unifiedviews.plugins.extractor.skgovcrz.SkGovCRZ.innerExecute(SkGovCRZ.java:170)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:133)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: www.crz.gov.sk: Name or service not known
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
at java.net.InetAddress.getAllByName0(InetAddress.java:1246)
at java.net.InetAddress.getAllByName(InetAddress.java:1162)
at java.net.InetAddress.getAllByName(InetAddress.java:1098)
at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:101)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
at eu.comsode.unifiedviews.plugins.extractor.skgovcrz.SkGovCRZ.getDetailInfo(SkGovCRZ.java:201)
at eu.comsode.unifiedviews.plugins.extractor.skgovcrz.SkGovCRZ.innerExecute(SkGovCRZ.java:147)
... 5 more
```

Instead of being an error of the DPU, it seems to be an error of the VM hosting UnifiedViews. Is that a correct assumption?

**Comment by mbl-eea-sk** [comment]
If other executions completed this can be caused by DNS server gone away or because the server hosting files to download became unaccessible.
I would not be surprised if their security policy automatically disconnects client after such long connection duration.

**Comment by jindrichmynarz** [comment]
Yesterday, I started the pipeline for the second time. So far it runs 27 hours without an error.

**Comment by jindrichmynarz** [comment]
Finally, the pipeline failed with a different exception:

```
Failed to prepare Context for DPURecord because of exception: cz.cuni.mff.xrg.odcs.backend.context.ContextException: Failed to create DataUnit.
at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.create(ContextFacade.java:54)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.bind(DPUExecutor.java:147)
at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.execute(Executor.java:317)
at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.run(Executor.java:432)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: eu.unifiedviews.dataunit.DataUnitException: No match in graph for ?o
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.getSingleObject(AbstractWritableMetadataDataUnit.java:512)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.access$000(AbstractWritableMetadataDataUnit.java:42)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit$4.execute(AbstractWritableMetadataDataUnit.java:327)
at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.innerExecute(FaultTolerantImpl.java:77)
at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.execute(FaultTolerantImpl.java:41)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.load(AbstractWritableMetadataDataUnit.java:307)
at cz.cuni.mff.xrg.odcs.backend.context.DataUnitManager.reload(DataUnitManager.java:207)
at cz.cuni.mff.xrg.odcs.backend.context.ContextRestorer.restore(ContextRestorer.java:29)
at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.create(ContextFacade.java:52)
... 8 more
```

This was accompanied with possibly relevant warnings. One from `org.openrdf.sail.helpers.DirectoryLockManager`:

```
Removing invalid lock 23466@jmynarz
```

And one from `org.openrdf.sail.nativerdf.NativeStoreConnection`:

```
Rolling back transaction due to connection close

Stack trace:
java.lang.Throwable null
   at org.openrdf.sail.helpers.SailConnectionBase.close(SailConnectionBase.java:245)
   at org.openrdf.repository.sail.SailRepositoryConnection.close(SailRepositoryConnection.java:147)
   at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.innerExecute(FaultTolerantImpl.java:92)
   at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.execute(FaultTolerantImpl.java:41)
   at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.load(AbstractWritableMetadataDataUnit.java:307)
   at cz.cuni.mff.xrg.odcs.backend.context.DataUnitManager.reload(DataUnitManager.java:207)
   at cz.cuni.mff.xrg.odcs.backend.context.ContextRestorer.restore(ContextRestorer.java:29)
   at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.create(ContextFacade.java:52)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.bind(DPUExecutor.java:147)
   at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.execute(Executor.java:317)
   at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.run(Executor.java:432)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
   at java.lang.Thread.run(Thread.java:745)
```

Can you see what might be the cause of these warnings?
